### ISSUE TITLE
Possible to not use method version?

### ISSUE THREAD

**Issue by ghost** [JJSaccolo/UIActivityIndicator-for-SDWebImage#1]
So I currently have SDWebImage implemented this way. 

[imageView setImageWithURL:[NSURL URLWithString:@"https://graph.facebook.com/olivier.poitrey/picture"]
          placeholderImage:[UIImage imageNamed:@"avatar-placeholder.png"]
                   options:SDWebImageRefreshCached];

I tried adding the "usingActivityIndicatorStyle:(UIActivityIndicatorViewStyle)activityStyle" after the options, but am getting an error 

"Use of undeclared identifier 'activityStyle'"

Anyway around this?

**Comment by JJSaccolo** [comment]
Hi :)

XCode is giving you an error because you're not setting a correct UIActivityIndicatorViewStyle. 
This syntax `(UIActivityIndicatorViewStyle)activityStyle` means that this method get a parameter named "activityStyle" of type `UIActivityIndicatorViewStyle`.

Short answer: change your method and write this: 

```
[aImageView setImageWithURL:[NSURL URLWithString:@"https://graph.facebook.com/olivier.poitrey/picture"]
          placeholderImage:[UIImage imageNamed:@"avatar-placeholder.png"]
                   options:SDWebImageRefreshCached
 usingActivityIndicatorStyle:UIActivityIndicatorViewStyleWhiteLarge];
```

You can choose between `UIActivityIndicatorViewStyleWhiteLarge`, `UIActivityIndicatorViewStyleWhite` and `UIActivityIndicatorViewStyleGray`.

**Comment by ivela-goorkers** [comment]
Hi. I am trying to use your category in my project and I have 2 doubts :)

First, wich is the header that I have to import if I am using it with pod.

Second, I've added your category to my project without pod and I am using this method:

[imageInTable setImageWithURL:[NSURL URLWithString:mydata.imageUrlString] usingActivityIndicatorStyle:UIActivityIndicatorViewStyleGray];

And everything works fine, but the activity indicator never shows. I am doing anything wrong?

**Comment by JJSaccolo** [comment]
Hello :)

1) Using CocoaPods you should import it in this way
`#import <UIActivityIndicator-for-SDWebImage/UIImageView+UIActivityIndicatorForSDWebImage.h>`

2) Uhm... can you please send me somehow more code? That method is correct and it should display the activityIndicatorView, if it's not doing it the problem could be somewhere else :)

**Comment by ivela-goorkers** [comment]
Hi, thanks for your response.

Now I have it running (it was a real mess of views in my table view that was hidding the activity indicator :D) with your files imported by hand.

But what I still can't is to get it running ussing CocoaPods. This is the content of my pod file:

platform :ios, '6.0'
pod 'SDWebImage', '~> 3.5.2'
pod 'UIActivityIndicator-for-SDWebImage'

When I run "pod install" it displays:

Analyzing dependencies
Downloading dependencies
Using SDWebImage (3.5.2)
Installing UIActivityIndicator-for-SDWebImage (1.0.3)
Generating Pods project
Integrating client project

Then I added the import that you said to me:
#import <UIActivityIndicator-for-SDWebImage/UIImageView+UIActivityIndicatorForSDWebImage.h>

When I compile my project everything seems fine but when I call this method [imageInTable setImageWithURL:[NSURL URLWithString:mydata.imageUrlString] usingActivityIndicatorStyle:UIActivityIndicatorViewStyleGray]; it crashes and the console output is: Uncaught exception: -[UIImageView setImageWithURL:usingActivityIndicatorStyle:]: unrecognized selector sent to instance

Is there any other thing that I could be forgetting to get it running with CocoaPods?

**Comment by JJSaccolo** [comment]
Unfortunately, it's hard to understand why this is not working :( 
If you please could send me your code (even an example project) I can look at it
