### ISSUE TITLE
extra code need to be comment

### ISSUE THREAD

**Issue by wenzizone** [JJSaccolo/UIActivityIndicator-for-SDWebImage#11]
hi
i just use this
it's a awsome plugin for SDWebImage
but when i using, i fount that some code needed to be comment
such as
[self setImageWithURL:url
         placeholderImage:placeholder
                  options:options
                 progress:progressBlock
                completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType) {
                    //completedBlock(image, error, cacheType);
                    [weakSelf removeActivityIndicator];
                }
     ];

completedBlock(image, error, cacheType); this part need to be comment, and didn't impact using

**Comment by JJSaccolo** [comment]
Ah, I see what's the problem. Yeah, you're probably passing nil as the completedBlock, and the app is crashing. 
Ok, I'll fix it. In the meantime you could just use a compledBlock empty ;)

**Comment by JJSaccolo** [comment]
Fixed in 1.0.5
