### ISSUE TITLE
The error in UIImageView+UIActivityIndicatorForSDWebImage.m

### ISSUE THREAD

**Issue by attolee** [JJSaccolo/UIActivityIndicator-for-SDWebImage#17]
![screen shot 2014-10-17 at 11 25 23 am](https://cloud.githubusercontent.com/assets/4199324/4674008/5f6162b2-55ad-11e4-9a75-13f530ccdba2.png)
I copy the files into project, using Xcode 6.

**Comment by mythodeia** [comment]
@AttoLee I just added them in my project where i use SDWebImage and i got no errors.
I believe this is the answer to your question:
http://stackoverflow.com/questions/16999749/expected-at-the-end-of-declaration-list

i tried to change the C Language Dialect to C99 and i got the same error as you, so make sure its default value is Compiler Default.

**Comment by attolee** [comment]
@mythodeia the error disappeared when i had changed the C Language Dialect to Compiler Default, thanks for your help.
i just wander is that possible to use GNU99 to compile one file, and meanwhile use default compiler to compile another file, the two file in the same project.

**Comment by mythodeia** [comment]
@AttoLee 
of the top of my head could you try the following:
Go in Build Phases tab on the Compile Sources and double tap on your file.
Then add the flag you want. Maybe like this: `-std=gnu99`
I am not sure about the syntax or the validity of this but i cannot think of anywhere else you might be able to add this kind of feature. 
Its like adding the `-fno-objc-arc` per file. So i guess it might work!
Why if i may ask you want this flag enabled for 1 file?

**Comment by attolee** [comment]
@mythodeia 
the project that i am working on is generated by Unity, of which C Language Dialect is C99.

![screen shot 2014-10-22 at 2 17 22 pm](https://cloud.githubusercontent.com/assets/4199324/4731961/89473b8c-59b4-11e4-823c-fb6792f57b50.png)

**Comment by mythodeia** [comment]
@AttoLee 
did you add the compiler flag `-std=gnu99` in the specific file you want?
Did it work?

**Comment by attolee** [comment]
@mythodeia 
i added the flag -std=gnu99 to UIImageView+UIActivityIndicatorForSDWebImage.m, more errors came.

![screen shot 2014-10-22 at 2 39 05 pm](https://cloud.githubusercontent.com/assets/4199324/4732075/55c0012a-59b6-11e4-87cc-c96d03d06849.png)

**Comment by mythodeia** [comment]
@AttoLee have you added all the necessary frameworks for SDWebImage to work properly?

**Comment by attolee** [comment]
@mythodeia thank you, i missed ImageIO.framework. and i added -ObjC to Other Linker Flags. but
![screen shot 2014-10-22 at 3 23 56 pm](https://cloud.githubusercontent.com/assets/4199324/4732499/c23671ee-59bc-11e4-855a-afc43b1d9c73.png)

**Comment by mythodeia** [comment]
@AttoLee i think the MapKit framework is missing..check it out

**Comment by attolee** [comment]
@mythodeia thank you again. i have added MapKit framework, all right now..

**Comment by mythodeia** [comment]
@AttoLee good luck with your project
