### ISSUE TITLE
Activity Spinner Not Centered

### ISSUE THREAD

**Issue by ghost** [JJSaccolo/UIActivityIndicator-for-SDWebImage#2]
After adding in your library, the activity icon is in the upper left, instead of the center. Never had this issue before. Any suggestions? Have autolayout enabled.

Code I am using:

```
self.image.contentMode = UIViewContentModeScaleAspectFit;

[self.image setImageWithURL:[NSURL URLWithString:imageString]
placeholderImage:nil
options:SDWebImageRefreshCached
usingActivityIndicatorStyle:UIActivityIndicatorViewStyleGray];
```

![img_0075](https://f.cloud.github.com/assets/1516560/535932/03817c74-c14e-11e2-98dc-adbd167b56b4.png)

**Comment by JJSaccolo** [comment]
Could you please NSLog your `self.image` size after the first line where you set the contentMode?

Just do a 

``` objective-c
NSLog(@"x:%f, y:%f, w:%f, h:%f", self.image.frame.origin.x, self.image.frame.origin.y, self.image.frame.size.width, self.image.frame.size.height);
```

**Comment by ghost** [comment]
Right after the contentMode line:
x:0.000000, y:44.000000, w:0.000000, h:0.000000
Right after the image is set with the url
x:6.000000, y:2.000000, w:40.000000, h:40.000000

In my story board the second one, 6, 2, 40 ,40 is what I have set for the UIImage box. The odd thing is it seems like it is not initialized or something. Maybe I need to set the frame before I load the setImageWithURL block?

**Comment by ghost** [comment]
aha! Setting the frame before the setImageWithUrl block worked!

```
[self.image setFrame:CGRectMake(6, 2, 40, 40)];
```

The weird thing is I wonder why the storyboard wasn't setting this ? 
I suspect it has something to do with iOS 6 "autolayout". I never had this issue in iOS5 without autolayout. It seems like ever since I turned that one everything got hosed, but have to support iPhone 5 so.. O well lol

Anyway thanks for the help!

**Comment by JJSaccolo** [comment]
Yes, that was the problem! 
The UIActvityIndicatorView is placed in the middle of the UIImageView... so, if the imageView is 0x0, the activityView will be placed in 0/2x0/2 (which is 0x0)! 
Glad you solved!
