### ISSUE TITLE
UIActivityIndicator not stopping on cancelCurrentImageLoad

### ISSUE THREAD

**Issue by aleufms** [JJSaccolo/UIActivityIndicator-for-SDWebImage#7]
The activityIndicator is not stopping when we cancel the image load.

**Comment by JJSaccolo** [comment]
Since this is a category and not a sublcass, I can't override `cancelCurrentImageLoad`.
But no worries, the solution is easy! Now the method `removeActivityindicator` is public, so you can call it (when you call `cancelCurrentImageLoad`). :)
